version: '3'
services:
    jenkins:
        container_name: jenkins
        build:
            context: ./dood
        ports:
            - 8080:8080
            - 50000:50000
        volumes:
            - ~/jenkins:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
            - /home/ubuntu/.ssh:/jenkins/.ssh
        restart: always
